# Generated by Django 4.2.25 on 2025-10-14 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('puesto_trabajo', models.CharField(max_length=100)),
                ('pago_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('septimo_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacaciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_cancelado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aguinaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insaforp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_real', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_utilidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesoftapp.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('movimiento_debe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movimiento_haber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesoftapp.cuenta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesoftapp.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='ResumenCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('haber_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_cuentas', to='codesoftapp.cuenta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesoftapp.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesoftapp.periodo')),
            ],
        ),
    ]
